# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "testmath.OperationRequest" do
    optional :a, :int32, 1
    optional :b, :int32, 2
  end
  add_message "testmath.OperationReply" do
    optional :result, :int32, 1
  end
end

module Testmath
  OperationRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("testmath.OperationRequest").msgclass
  OperationReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("testmath.OperationReply").msgclass
end
