# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: rpc.proto for package 'testmath'

require 'grpc'
require 'rpc'

module Testmath
  module Calculator

    # TODO: add proto service documentation here
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'testmath.Calculator'

      rpc :Add, OperationRequest, OperationReply
      rpc :Multiply, OperationRequest, OperationReply
    end

    Stub = Service.rpc_stub_class
  end
end
