%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.22.5

-ifndef(math_pb).
-define(math_pb, true).

-define(math_gpb_version, "3.22.5").

-ifndef('OPERATIONREPLY_PB_H').
-define('OPERATIONREPLY_PB_H', true).
-record('OperationReply',
        {result                         % = 1, int32
        }).
-endif.

-ifndef('OPERATIONREQUEST_PB_H').
-define('OPERATIONREQUEST_PB_H', true).
-record('OperationRequest',
        {a,                             % = 1, int32
         b                              % = 2, int32
        }).
-endif.

-endif.
