%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.22.5

-ifndef(rpc_pb).
-define(rpc_pb, true).

-define(rpc_pb_gpb_version, "3.22.5").

-ifndef('DISCONNECTRESPONSE_PB_H').
-define('DISCONNECTRESPONSE_PB_H', true).
-record('DisconnectResponse',
        {status                 :: 'ERROR' | 'SUCCESS' % = 1, enum Status
        }).
-endif.

-ifndef('COMMANDRESPONSE_PB_H').
-define('COMMANDRESPONSE_PB_H', true).
-record('CommandResponse',
        {status                 :: 'ERROR' | 'SUCCESS', % = 1, enum Status
         disconnect             :: boolean(),       % = 2
         stop_streams           :: boolean(),       % = 3
         stream_from            :: boolean(),       % = 4
         stream_id              :: binary(),        % = 5
         transmissions = []     :: [binary()]       % = 6
        }).
-endif.

-ifndef('COMMANDMESSAGE_PB_H').
-define('COMMANDMESSAGE_PB_H', true).
-record('CommandMessage',
        {command                :: binary(),        % = 1
         identifier             :: binary(),        % = 2
         connection_identifiers :: binary(),        % = 3
         data                   :: binary()         % = 4
        }).
-endif.

-ifndef('CONNECTIONRESPONSE_PB_H').
-define('CONNECTIONRESPONSE_PB_H', true).
-record('ConnectionResponse',
        {status                 :: 'ERROR' | 'SUCCESS', % = 1, enum Status
         identifiers            :: binary(),        % = 2
         transmissions = []     :: [binary()]       % = 3
        }).
-endif.

-ifndef('CONNECTIONREQUEST_PB_H').
-define('CONNECTIONREQUEST_PB_H', true).
-record('ConnectionRequest',
        {path                   :: binary(),        % = 1
         headers = []           :: [{binary(), binary()}] % = 2
        }).
-endif.

-ifndef('DISCONNECTREQUEST_PB_H').
-define('DISCONNECTREQUEST_PB_H', true).
-record('DisconnectRequest',
        {identifiers            :: binary(),        % = 1
         subscriptions = []     :: [binary()]       % = 2
        }).
-endif.

-endif.
