// Code generated by protoc-gen-go.
// source: rpc.proto
// DO NOT EDIT!

/*
Package testmath is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	OperationRequest
	OperationReply
*/
package testmath

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OperationRequest struct {
	A int32 `protobuf:"varint,1,opt,name=a" json:"a,omitempty"`
	B int32 `protobuf:"varint,2,opt,name=b" json:"b,omitempty"`
}

func (m *OperationRequest) Reset()                    { *m = OperationRequest{} }
func (m *OperationRequest) String() string            { return proto.CompactTextString(m) }
func (*OperationRequest) ProtoMessage()               {}
func (*OperationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type OperationReply struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *OperationReply) Reset()                    { *m = OperationReply{} }
func (m *OperationReply) String() string            { return proto.CompactTextString(m) }
func (*OperationReply) ProtoMessage()               {}
func (*OperationReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*OperationRequest)(nil), "testmath.OperationRequest")
	proto.RegisterType((*OperationReply)(nil), "testmath.OperationReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Calculator service

type CalculatorClient interface {
	Add(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationReply, error)
	Multiply(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationReply, error)
}

type calculatorClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorClient(cc *grpc.ClientConn) CalculatorClient {
	return &calculatorClient{cc}
}

func (c *calculatorClient) Add(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationReply, error) {
	out := new(OperationReply)
	err := grpc.Invoke(ctx, "/testmath.Calculator/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorClient) Multiply(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationReply, error) {
	out := new(OperationReply)
	err := grpc.Invoke(ctx, "/testmath.Calculator/Multiply", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Calculator service

type CalculatorServer interface {
	Add(context.Context, *OperationRequest) (*OperationReply, error)
	Multiply(context.Context, *OperationRequest) (*OperationReply, error)
}

func RegisterCalculatorServer(s *grpc.Server, srv CalculatorServer) {
	s.RegisterService(&_Calculator_serviceDesc, srv)
}

func _Calculator_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testmath.Calculator/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Add(ctx, req.(*OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calculator_Multiply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Multiply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testmath.Calculator/Multiply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Multiply(ctx, req.(*OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Calculator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "testmath.Calculator",
	HandlerType: (*CalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Calculator_Add_Handler,
		},
		{
			MethodName: "Multiply",
			Handler:    _Calculator_Multiply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x2a, 0x48, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x28, 0x49, 0x2d, 0x2e, 0xc9, 0x4d, 0x2c, 0xc9, 0x50,
	0xd2, 0xe3, 0x12, 0xf0, 0x2f, 0x48, 0x2d, 0x4a, 0x2c, 0xc9, 0xcc, 0xcf, 0x0b, 0x4a, 0x2d, 0x2c,
	0x05, 0x8a, 0x0b, 0xf1, 0x70, 0x31, 0x26, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x31, 0x26,
	0x82, 0x78, 0x49, 0x12, 0x4c, 0x10, 0x5e, 0x92, 0x92, 0x06, 0x17, 0x1f, 0x92, 0xfa, 0x82, 0x9c,
	0x4a, 0x21, 0x31, 0x2e, 0xb6, 0xa2, 0xd4, 0xe2, 0xd2, 0x9c, 0x12, 0xa8, 0x16, 0x28, 0xcf, 0xa8,
	0x9f, 0x91, 0x8b, 0xcb, 0x39, 0x31, 0x27, 0xb9, 0x34, 0x27, 0xb1, 0x24, 0xbf, 0x48, 0xc8, 0x96,
	0x8b, 0xd9, 0x31, 0x25, 0x45, 0x48, 0x4a, 0x0f, 0x66, 0xb5, 0x1e, 0xba, 0xbd, 0x52, 0x12, 0x58,
	0xe5, 0x80, 0x76, 0x28, 0x31, 0x08, 0x39, 0x71, 0x71, 0xf8, 0x02, 0x4d, 0xcd, 0x04, 0xd9, 0x48,
	0xa6, 0x19, 0x49, 0x6c, 0x60, 0xcf, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x7d, 0x70,
	0x04, 0x09, 0x01, 0x00, 0x00,
}
